apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: ecommerce-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecommerce-client
  template:
    metadata:
      labels:
        app: ecommerce-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://ecommerce-server-server:3000" 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
