apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: ecommerce-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ecommerce-client
