stages:
  - build
  - lint
  - test
  - push
  - deploy
  

# Use Docker image with Docker CLI pre-installed
image: docker:20.10.16

# Use Docker-in-Docker service to enable Docker commands
services:
  - docker:20.10.16-dind

# Define environment variables for Docker
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA # Use short commit hash as the image tag
  NODE_MODULES_CACHE_KEY: ${CI_COMMIT_REF_SLUG}
  DOCKER_BUILDKIT: "1"  # Enable BuildKit for better caching
  DOCKER_TLS_CERTDIR: ""  # Fix for DinD

cache: &global_cache
  key: ${NODE_MODULES_CACHE_KEY}
  paths:
    - client/node_modules/
    - server/node_modules/
  policy: pull-push

# Include GitLab's built-in SAST template
include:
  - template: Security/SAST.gitlab-ci.yml

# Add SAST configuration
sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"
    SCAN_KUBERNETES_MANIFESTS: "false"
  before_script: []  # Override the global before_script
  script:
    - /analyzer run
  dependencies: []
  artifacts:
    reports:
      sast: gl-sast-report.json

# Authenticate with Docker Hub
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker info # Validate Docker environment

# Build Client Container
build_client:
  stage: build
  script:
    - cd client
    - docker build -t $DOCKER_USERNAME/ecoommerce-application-client:latest .
    - docker images 
  cache:
    <<: *global_cache
    policy: pull-push
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Build Server Container
build_server:
  stage: build
  script:
    - cd server
    - docker build -t $DOCKER_USERNAME/ecoommerce-application-server:latest .
    - docker images 
  cache:
    <<: *global_cache
    policy: pull-push
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Run Linting
lint_code:
  stage: lint
  image: node:16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - apt-get update && apt-get install -y docker.io
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - npm install eslint
    # - npx eslint client --config eslint.config.js
    # - cd ../server && npx eslint .
  cache:
    <<: *global_cache
    policy: pull
  timeout: 30m
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Run Unit Tests
unit_tests:
  stage: test
  script:
    # Run Unit Tests for Client
    - cd client
    - docker run --rm $DOCKER_USERNAME/ecoommerce-application-client:latest npm test || echo "No tests found in client."
    # Run Unit Tests for Server
    - cd ../server
    - docker run --rm $DOCKER_USERNAME/ecoommerce-application-server:latest npm test || echo "No tests found in server."
  artifacts:
    when: always
    paths:
      - client/test-results.xml
      - server/test-results.xml
  needs:
    - build_client
    - build_server
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Push Docker Images to Docker Hub
push_images:
  stage: push
  script:
    - cd client
    - docker build -t $DOCKER_USERNAME/ecoommerce-application-client:latest .
    - docker push $DOCKER_USERNAME/ecoommerce-application-client:latest
    
    - cd ../server
    - docker build -t $DOCKER_USERNAME/ecoommerce-application-server:latest .
    - docker push $DOCKER_USERNAME/ecoommerce-application-server:latest
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  needs:
    - unit_tests
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Add these new deployment jobs
.deploy_template: &deploy_template
  image: 
    name: amazon/aws-cli:latest
  before_script:
    # Install required packages
    - yum install -y curl
    
    # Install Helm
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    
    # Install kubectl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl 
    - mv kubectl /usr/local/bin/
    
    # Configure AWS credentials and region
    - aws configure set region us-east-1
    - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
    - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
    - aws configure set output json
    
    # Verify AWS configuration
    - aws sts get-caller-identity
    
    # Configure kubectl
    - aws eks --region us-east-1 update-kubeconfig --name ecommerce-cluster
    
    # Verify kubectl configuration
    - kubectl get svc

deploy_client:
  <<: *deploy_template
  stage: deploy
  script:
    # Debug information
    - pwd
    - ls -la
    # Install git to clone helm charts if needed
    - yum install -y git
    # Deploy using helm
    - >
      helm upgrade --install ecommerce-client ./helm/client 
      --set image.repository=${DOCKER_USERNAME}/ecoommerce-application-client
      --set image.tag=latest
      --set service.type=LoadBalancer
      --namespace default
      --create-namespace
      --wait
  needs:
    - push_images
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy_server:
  <<: *deploy_template
  stage: deploy
  script:
    # Debug information
    - pwd
    - ls -la
    # Install git to clone helm charts if needed
    - yum install -y git
    # Deploy using helm
    - >
      helm upgrade --install ecommerce-server ./helm/server 
      --set image.repository=${DOCKER_USERNAME}/ecoommerce-application-server
      --set image.tag=latest
      --namespace default
      --create-namespace
      --wait
  needs:
    - push_images
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

default:
  timeout: 1h
