# client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: your-dockerhub-username/client:v1
          ports:
            - containerPort: 8080
---
# client-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: ecommerce
spec:
  selector:
    app: client
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
