version: '3'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/usr/src/app # Mount local client code to container for live reloading
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    # restart: always
    networks:
      - app-network
    

  server:
    build: ./server
    container_name: server
    environment:
      - PORT=3001
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET='waghib30 '
      - MONGO_URI=mongodb://mongo:27017/mern_ecommerce
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/src/app # Mount local server code to container for live reloading
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge