apiVersion: v2
name: monitoring
description: A Helm chart for Prometheus and Grafana monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: 19.7.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.57.4
    repository: https://grafana.github.io/helm-charts
