apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://waghib:W1032m30012003.@ecommerce.nk5mf.mongodb.net/mern-ecommerce?retryWrites=true&w=majority&appName=ecommerce"
