apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: ecommerce-server
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 3000
      protocol: TCP
      name: metrics
  selector:
    app: ecommerce-server
