apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-server
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ecommerce-server
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
