replicaCount: 2

image:
  repository: waghib/ecoommerce-application-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  name: ecommerce-server

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  hosts:
    - host: api.ecommerce.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  - name: PORT
    value: "5000"
  - name: MONGODB_URI
    value: "mongodb://mongodb:27017/ecommerce"
  - name: JWT_SECRET
    value: "waghib"
