replicaCount: 2

image:
  repository: waghib/ecoommerce-application-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  name: ecommerce-server

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  hosts:
    - host: api.ecommerce.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  - name: PORT
    value: "3000"
  - name: BASE_API_URL
    value: "api"
  - name: CLIENT_URL
    value: "http://34.58.79.83"
  - name: MONGO_URI
    value: "mongodb+srv://waghib:W1032m30012003.@ecommerce.nk5mf.mongodb.net/mern-ecommerce?retryWrites=true&w=majority&appName=ecommerce"
  - name: JWT_SECRET
    value: "waghib"
