replicaCount: 2

image:
  repository: waghib/ecoommerce-application-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

mongodb:
  uri: ${var.mongodb_uri}

jwt:
  secret: "waghib"
