replicaCount: 2

image:
  repository: waghib/ecoommerce-application-client
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
