replicaCount: 2

image:
  repository: waghib/ecoomerce-application-client
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  - name: API_URL
    value: "http://34.58.79.83/api"
  - name: REACT_APP_API_URL
    value: "http://34.58.79.83/api"

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  hosts:
    - host: ecommerce.local
      paths:
        - path: /
          pathType: Prefix
