# Default values for mern-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set the number of replicas for your app
replicaCount: 1

# Container image settings for the server
image:
  repository: waghib/ecoomerce-application-server  # Update with your server image
  pullPolicy: IfNotPresent
  tag: "latest"  # Or specify a version

# Image settings for the client
clientImage:
  repository: waghib/ecoomerce-application-client  # Update with your client image
  pullPolicy: IfNotPresent
  tag: "latest"  # Or specify a version

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Service settings
service:
  type: ClusterIP
  port: 80

# Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

# Liveness and readiness probes for the server
livenessProbe:
  httpGet:
    path: /health  # Adjust this to a health-check route
    port: http
readinessProbe:
  httpGet:
    path: /health  # Adjust this to a health-check route
    port: http

# Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Volume and volumeMount settings (if needed)
volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
