apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-app.fullname" . }}
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mern-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mern-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mern-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        # Node.js Backend Container
        - name: mern-backend  # Change to a suitable name for the backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}  # Adjust this if your backend listens on a different port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health  # Adjust this path as necessary for your backend health check
              port: http
          readinessProbe:
            httpGet:
              path: /health  # Adjust this path as necessary for your backend readiness check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        # React Frontend Container
        - name: mern-frontend  # Change to a suitable name for the frontend
          image: "{{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag | default .Chart.AppVersion }}"  # Use the client image defined in values.yaml
          imagePullPolicy: {{ .Values.clientImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080   # Adjust to your frontend's listening port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /  # Adjust this path as necessary for your frontend health check
              port: http
          readinessProbe:
            httpGet:
              path: /  # Adjust this path as necessary for your frontend readiness check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
