apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Name prefix for resources
# namePrefix: "ecommerces-"

# Define the resources to include
resources:
  - client-deployment.yaml
  - client-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - configmap.yaml
  - secrets.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - client-ingress.yaml
  - namespace.yaml