apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  JWT_SECRET: d2FnaGliMzA=
  MONGO_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L21lcm5fZWNvbW1lcmNl
  # MAILGUN_API_KEY: {{ MAILGUN_API_KEY in base64 }}
  # GOOGLE_CLIENT_ID: {{ GOOGLE_CLIENT_ID in base64 }}
  # FACEBOOK_CLIENT_ID: {{ FACEBOOK_CLIENT_ID in base64 }}