apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: server
          image: waghib/ecommerce-server:latest
          ports:
            - containerPort: 3001
          env:
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: BASE_API_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_URI
